baseURL = 'https://www.vbtronic.com/'
languageCode = 'en-us'
title = 'Viktor Brunclík'
enableRobotsTXT = true
enableEmoji = false
disableKinds = ['RSS']
taxonomies = {}

[params]
  description = "Viktor Brunclík — vbtronic.com"
  author = "Viktor Brunclík"

[markup]
  [markup.highlight]
    style = 'monokai'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'News'
    url = '/news/'
    weight = 2
  [[menu.main]]
    name = 'Products & Websites'
    url = '/products/'
    weight = 3
  [[menu.main]]
    name = 'Analyses'
    url = '/analysis/'
    weight = 4
  [[menu.main]]
    name = 'About Viktor Brunclík'
    url = '/about/'
    weight = 5
  [[menu.main]]
    name = 'Posts'
    url = '/posts/'
    weight = 6
  [[menu.main]]
    name = 'Portfolio'
    url = '/portfolio/'
    weight = 7
  [[menu.main]]
    name = 'Contact'
    url = '/contact/'
    weight = 8
  [[menu.main]]
    name = 'Help'
    url = '/help/'
    weight = 9
  [[menu.main]]
    name = 'Privacy Policy'
    url = '/privacy/'
    weight = 10
